command! Nvterm lua require'nvterm'.run('', '')
command! NvtermVSplit lua require'nvterm'.run('v', '')
command! NvtermHSplit lua require'nvterm'.run('h', '')
command! Unittest lua require'nvterm'.run('h', 'python unittest')
command! FlaskApp lua require'nvterm'.run('h', 'start flaskapp')
command! Behave lua require'nvterm'.run('h', 'behave')
